name: notifications-cron
on:
  schedule:
    - cron: "0 */12 * * *" # every 12th hour
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our notifications cron api
        run: |
          curl --request POST \
          --url 'https://rinkeby.withbacked.xyz/api/cron/notifications' \
          --header "Authorization: Basic $(echo -n username:${{ secrets.EVENTS_API_SECRET_KEY }} | base64)"