name: notifications-cron
on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our notifications sqs consumer api
        run: |
          curl --request POST \
          --url 'https://nft-pawn-shop-rinkeby.vercel.app/api/cron/sqsConsumer' \
          --header 'Authorization: Bearer ${{ secrets.NOTIFICATIONS_CRON_API_SECRET_KEY }}'